name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: install-deps
        name: Install dependencies
        run: |
          yarn install
      - id: biome
        name: Run biome
        run: |
          yarn biome ci .
